#!/usr/bin/env python3
"""Generates the English page and the sitemap from public/index.html.

public/index.html is the single source of truth. It carries the German copy in its markup and
both languages in its `i18n` object; this script renders the English variant to public/en.html so
that search engines get a real, indexable English URL instead of a language switch that only
exists in JavaScript.

Run `python3 tools/build.py` after editing the page, or `--check` (what CI does) to verify the
generated files still match the source.

Stdlib only, on purpose: this repository has no build step at deploy time and no dependencies.
"""

from __future__ import annotations

import datetime
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "public" / "index.html"
EN_PAGE = ROOT / "public" / "en.html"
SITEMAP = ROOT / "public" / "sitemap.xml"
ORIGIN = "https://lktec.org"

GENERATED_NOTE = "<!-- Generated by tools/build.py from index.html - do not edit by hand. -->"


def js_object_to_json(src: str) -> str:
    """Turn a JS object literal with unquoted identifier keys into strict JSON.

    Walks character by character and tracks string boundaries, because a naive regex also
    rewrites the `https:` inside project URLs and silently corrupts the data.
    """
    out: list[str] = []
    i, n = 0, len(src)
    in_string = False
    quote = ""
    while i < n:
        c = src[i]
        if in_string:
            if c == "\\" and i + 1 < n:
                out.append(c)
                out.append(src[i + 1])
                i += 2
                continue
            if c == quote:
                in_string = False
                out.append('"')
            else:
                out.append(c)
            i += 1
            continue
        if c in "\"'":
            in_string, quote = True, c
            out.append('"')
            i += 1
            continue
        if c.isalpha() or c == "_":
            m = re.match(r"([A-Za-z_$][A-Za-z0-9_$]*)\s*:", src[i:])
            preceding = "".join(out).rstrip()
            if m and (preceding.endswith(("{", ",")) or not preceding):
                out.append('"' + m.group(1) + '":')
                i += m.end()
                continue
        out.append(c)
        i += 1
    return "".join(out)


def read_i18n(html: str) -> dict:
    start = html.index("const i18n = {")
    end = html.index("\n};", start) + len("\n};")
    literal = html[start + len("const i18n = "): end].rstrip().rstrip(";")
    data = json.loads(js_object_to_json(literal))
    missing = set(data["de"]) ^ set(data["en"])
    if missing:
        raise SystemExit("i18n keys differ between de and en: " + repr(sorted(missing)))
    return data


def esc(text: str) -> str:
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))


def replace_i18n_elements(html: str, strings: dict) -> str:
    """Swap the inner HTML of every [data-i18n] element for its translation."""
    pattern = re.compile(r'(<([a-z0-9]+)\b[^>]*\bdata-i18n="([^"]+)"[^>]*>)(.*?)(</\2>)', re.S)

    def repl(m):
        key = m.group(3)
        if key not in strings:
            raise SystemExit('element carries data-i18n="' + key + '" but the i18n object has no such key')
        return m.group(1) + strings[key] + m.group(5)

    out, count = pattern.subn(repl, html)
    expected = len(re.findall(r"data-i18n=", html))
    if count != expected:
        raise SystemExit("translated {} of {} data-i18n elements - check for nested tags".format(count, expected))
    return out


def build_en(html: str, i18n: dict) -> str:
    en = i18n["en"]
    out = html

    replacements = [
        ('<html lang="de">', '<html lang="en">'),
        # Canonical and og:url must point at the English URL, otherwise both pages claim to be
        # the same document and Google drops one of them.
        ('<link rel="canonical" href="https://lktec.org/">',
         '<link rel="canonical" href="https://lktec.org/en">'),
        ('<meta property="og:url" content="https://lktec.org/">',
         '<meta property="og:url" content="https://lktec.org/en">'),
        ('<meta property="og:locale" content="de_DE">',
         '<meta property="og:locale" content="en_US">'),
        ('<meta property="og:locale:alternate" content="en_US">',
         '<meta property="og:locale:alternate" content="de_DE">'),
        ('<a id="btn-de" class="active" href="/" hreflang="de">DE</a>',
         '<a id="btn-de" href="/" hreflang="de">DE</a>'),
        ('<a id="btn-en" href="/en" hreflang="en">EN</a>',
         '<a id="btn-en" class="active" href="/en" hreflang="en">EN</a>'),
        ('"url": "https://lktec.org/"', '"url": "https://lktec.org/en"'),
    ]
    for old, new in replacements:
        if out.count(old) != 1:
            raise SystemExit("expected exactly one occurrence of " + repr(old) + " in the source page")
        out = out.replace(old, new)

    for prop, value in (("og:title", en["meta_title"]), ("og:description", en["meta_desc"])):
        out = re.sub(r'(<meta property="' + prop + r'" content=")[^"]*(">)',
                     lambda m, v=value: m.group(1) + esc(v) + m.group(2), out, count=1)
    for name, value in (("description", en["meta_desc"]),
                        ("twitter:title", en["meta_title"]),
                        ("twitter:description", en["meta_desc"])):
        out = re.sub(r'(<meta name="' + name + r'" content=")[^"]*(">)',
                     lambda m, v=value: m.group(1) + esc(v) + m.group(2), out, count=1)

    out = re.sub(r"<title>.*?</title>", "<title>" + esc(en["meta_title"]) + "</title>",
                 out, count=1, flags=re.S)
    out = replace_i18n_elements(out, en)
    out = out.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + GENERATED_NOTE, 1)
    return out


def last_modified() -> str:
    """The day the sitemap is generated.

    Deriving this from git history is circular: generating the sitemap, committing it and then
    re-deriving the value yields a different answer, so a consistent committed state is
    unreachable - and a squash merge would move the date again and break CI on main. The build
    date stays honest by a different route: any edit to public/index.html also changes the
    generated English page, whose drift check forces a regeneration, which updates this date.
    """
    return datetime.date.today().isoformat()


def build_sitemap() -> str:
    day = last_modified()
    entries = []
    # Each URL declares itself and its alternate: on a multilingual site Google wants the
    # hreflang set repeated in the sitemap, the link elements in the pages are not enough.
    for loc, lang, alt_loc, alt_lang in ((ORIGIN + "/", "de", ORIGIN + "/en", "en"),
                                         (ORIGIN + "/en", "en", ORIGIN + "/", "de")):
        entries.append(
            "  <url>\n"
            "    <loc>" + loc + "</loc>\n"
            '    <xhtml:link rel="alternate" hreflang="' + lang + '" href="' + loc + '"/>\n'
            '    <xhtml:link rel="alternate" hreflang="' + alt_lang + '" href="' + alt_loc + '"/>\n'
            '    <xhtml:link rel="alternate" hreflang="x-default" href="' + ORIGIN + '/"/>\n'
            "    <lastmod>" + day + "</lastmod>\n"
            "    <changefreq>monthly</changefreq>\n"
            "    <priority>1.0</priority>\n"
            "  </url>"
        )
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
            '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
            + "\n".join(entries) + "\n</urlset>\n")


def ignore_lastmod(text: str) -> str:
    """Everything but the <lastmod> value - that date is the build day and must not, on its own,
    mark the file as drifted."""
    return re.sub(r"<lastmod>[^<]*</lastmod>", "<lastmod/>", text)


def main() -> int:
    check = "--check" in sys.argv[1:]
    html = SOURCE.read_text(encoding="utf-8")
    i18n = read_i18n(html)

    stale = []
    page_changed = False

    for path, content, compare in ((EN_PAGE, build_en(html, i18n), str),
                                   (SITEMAP, build_sitemap(), ignore_lastmod)):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        # The sitemap's own structure rarely changes, so comparing it alone would keep a stale
        # <lastmod> forever. Refresh it whenever the page itself was rewritten.
        unchanged = current is not None and compare(current) == compare(content) and not (
            path is SITEMAP and page_changed
        )
        if unchanged:
            print(str(path.relative_to(ROOT)) + ": up to date")
            continue
        if check:
            # In --check the date alone must never fail the build; a changed page already shows
            # up as a difference on the English page itself.
            if path is SITEMAP and ignore_lastmod(current or "") == ignore_lastmod(content):
                print(str(path.relative_to(ROOT)) + ": up to date")
                continue
            stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(str(path.relative_to(ROOT)) + ": written")
        if path is EN_PAGE:
            page_changed = True

    for path in stale:
        print("::error::" + str(path) + " is out of date - run 'python3 tools/build.py' and commit the result")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
